# -*- coding: utf-8 -*-
"""mnist_model.h5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xQFBLY44H497QXzWjpZ_Wbw7vuYEKRkx
"""

import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.utils import to_categorical

# โหลด MNIST Dataset
(X_train, y_train), (X_test, y_test) = mnist.load_data()
X_train, X_test = X_train / 255.0, X_test / 255.0

# แปลง Label เป็น One-Hot Encoding
y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)

# สร้างโมเดล MLP สำหรับ MNIST
mnist_model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(128, activation='relu'),
    Dense(64, activation='relu'),
    Dense(10, activation='softmax')
])

# คอมไพล์และฝึกสอนโมเดล
mnist_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
mnist_model.fit(X_train, y_train, epochs=10, batch_size=64, validation_data=(X_test, y_test))

# บันทึกโมเดล
mnist_model.save("mnist_model.h5")