# -*- coding: utf-8 -*-
"""web_app_ml_nn

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j1YKHrYAtT4TVvdPqTS9SWJNncpYIdje
"""

import streamlit as st
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import mnist, cifar10
from tensorflow.keras.models import load_model
import matplotlib.pyplot as plt

# โหลดโมเดลที่ฝึกไว้
mnist_model = load_model("mnist_model.h5")
cifar10_model = load_model("cifar10_model.h5")

# โหลดข้อมูลตัวอย่าง MNIST และ CIFAR-10
(_, _), (X_mnist, _) = mnist.load_data()
(_, _), (X_cifar, _) = cifar10.load_data()
X_mnist = X_mnist.astype("float32") / 255.0
X_cifar = X_cifar.astype("float32") / 255.0
X_mnist = X_mnist.reshape(-1, 28, 28, 1)

# สร้างหน้าเว็บ Streamlit
st.title("Machine Learning & Neural Network Web App")

# สร้าง Sidebar เลือกหน้า
page = st.sidebar.selectbox("เลือกหน้า:", ["📊 ข้อมูล & ทฤษฎี", "🤖 ทดสอบ MNIST Model", "🖼️ ทดสอบ CIFAR-10 Model"])

if page == "📊 ข้อมูล & ทฤษฎี":
    st.header("📊 ข้อมูลและทฤษฎีการพัฒนาโมเดล")
    st.write("### 1️⃣ การเตรียมข้อมูล")
    st.write("- MNIST: ตัวเลขขนาด 28x28 พิกเซล\n- CIFAR-10: ภาพขนาด 32x32 พิกเซล 10 หมวดหมู่")
    st.write("### 2️⃣ ทฤษฎีของอัลกอริทึม")
    st.write("- MNIST: ใช้ SVM, KNN, Random Forest\n- CIFAR-10: ใช้ CNN")

elif page == "🤖 ทดสอบ MNIST Model":
    st.header("🤖 ทดสอบ MNIST Model")
    index = st.slider("เลือกภาพ (0-9999):", 0, 9999, 0)
    image = X_mnist[index]
    pred = mnist_model.predict(image.reshape(1, 28, 28, 1))
    label = np.argmax(pred)
    st.image(image.reshape(28, 28), caption=f"Prediction: {label}", width=150)

elif page == "🖼️ ทดสอบ CIFAR-10 Model":
    st.header("🖼️ ทดสอบ CIFAR-10 Model")
    class_names = ["airplane", "automobile", "bird", "cat", "deer", "dog", "frog", "horse", "ship", "truck"]
    index = st.slider("เลือกภาพ (0-9999):", 0, 9999, 0)
    image = X_cifar[index]
    pred = cifar10_model.predict(image.reshape(1, 32, 32, 3))
    label = class_names[np.argmax(pred)]
    st.image(image, caption=f"Prediction: {label}", width=150)